---
title: "Honor's Thesis"
author: "Niklas Blanadet"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# install.packages("tidyverse",
#                  "ggpubr",
#                  "FSA",
#                  "rcompanion",
#                  "multcomp",
#                  "lsmeans",
#                  "ggthemes",
#                  "httr",
#                  "tm",
#                  "tmap",
#                  "sf",
#                  "sp",
#                  "purrr",
#                  "raster",
#                  "rgbif", 
#                  "patchwork")

library("tidyverse")
library("ggpubr")
library("FSA")
library("rcompanion")
library("multcomp")
library("lsmeans")
library("ggthemes")
library("tmap")
library("tm")
library("httr")
library("sf")
library("sp")
library("purrr")
library("raster")
library("rgbif")
library("patchwork")
```

```{r}
# Read in water data
water_data <- tibble(read.csv("C:/Users/nblan/Desktop/Honors_Project/R/project_data.csv"))
water_data$sample_type[data$sample_type == "well water"] <- "well_water"
water_data <- water_data %>%
  drop_na(dD, dO)

# Read in C and N data
c_n_data <- tibble(read.csv("C:/Users/nblan/Desktop/Honors_Project/R/project_c_n_data.csv"))

# Read in Manzanita locations
manzanita <- read.csv("C:/Users/nblan/Desktop/Honors_Project/R/manzanita_data.csv")
```

# Using temporal scale

```{r}
# Adjust the dates
temporal_data <- water_data
temporal_data$date[temporal_data$date == "11/24/2020"] <- "12/6/2020"

coeff <- 10

temporal_data %>%
  filter(sample_type == c("Core", "Twig")) %>%
  ggplot(aes(x = date, y = dD, col = sample_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Sampling Date", y = "δD (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Sample Type") +
  ggsave("temporal_core_twig_d2H.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)

temporal_data %>%
  filter(sample_type == c("Core", "Twig")) %>%
  ggplot(aes(x = date, y = dO, col = sample_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Sampling Date", y = "δ18O (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Sample Type") +
  ggsave("temporal_core_twig_d18O.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)
  
temporal_data %>%
  filter(sample_type == "Core") %>%
  ggplot(aes(x = date, y = dD, col = plant_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Date", y = "δD (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Plant Type") +
  ggsave("temporal_resprout_notresprout_core_d2H.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)

temporal_data %>%
  filter(sample_type == "Core") %>%
  ggplot(aes(x = date, y = dO, col = plant_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Date", y = "δ18O (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Plant Type") +
  ggsave("temporal_resprout_notresprout_core_d18O.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)

temporal_data %>%
  filter(sample_type == "Twig") %>%
  ggplot(aes(x = date, y = dD, col = plant_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Date", y = "δD (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Plant Type") +
  ggsave("temporal_resprout_notresprout_twig_d2H.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)

temporal_data %>%
  filter(sample_type == "Twig") %>%
  ggplot(aes(x = date, y = dO, col = plant_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Date", y = "δ18O (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Plant Type") +
  ggsave("temporal_resprout_notresprout_twig_d18O.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)
```

```{r}
# CORES VS TWIGS (dD)

temporal_data %>%
  filter(sample_type == c("Core", "Twig"), plant_type == "not_resprout") %>%
  ggplot(aes(x = date, y = dD, col = sample_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Sampling Date", y = "δD (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Sample Type") +
  ggsave("temporal_core_twig_not_resprout_d2H.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)

temporal_data %>%
  filter(sample_type == c("Core", "Twig"), plant_type == "resprout") %>%
  ggplot(aes(x = date, y = dD, col = sample_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(x = "Sampling Date", y = "δD (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Sample Type") +
  ggsave("temporal_core_twig_resprout_d2H.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)




```


# Dual isotope plots

```{r}
# Make new water object data

new_water_data <- water_data %>%
  mutate(full_sample_type = paste(sample_type, plant_type, sep = "_"))

new_water_data %>%
  filter(sample_type %in% c("Twig", "well_water", "precip", "Soil")) %>%
  ggplot(aes(x = dO, y = dD, col = full_sample_type)) +
    geom_point(alpha = 1, show.legend = FALSE) +
    stat_ellipse() +
    geom_abline(aes(slope = 7.82, intercept = 9.42, lty = "Local Meteoric Water Line")) +
    labs(x = "δ18O (‰)", y = "δD (‰)") +
    theme_pubr(legend = "right") +
    scale_color_discrete(name = "Sample Type") +
    scale_linetype(name = "Local Meteoric Water Line") +
    ggsave("δD_and_d18O_full_twig_graph.png", 
           path = "C:/Users/nblan/Desktop/Honors_project/R/Graphs", 
           height = 6, 
           width = 10)


new_water_data %>%
  filter(sample_type %in% c("Core", "well_water", "precip", "Soil")) %>%
  ggplot(aes(x = dO, y = dD, col = full_sample_type)) +
    geom_point(alpha = 1, show.legend = FALSE) +
    stat_ellipse() +
    geom_abline(aes(slope = 7.82, intercept = 9.42, lty = "Local Meteoric Water Line")) +
    labs(x = "δ18O (‰)", y = "δD (‰)") +
    theme_pubr(legend = "right") +
    scale_color_discrete(name = "Sample Type") +
    scale_linetype(name = "Local Meteoric Water Line") +
    ggsave("δD_and_d18O_full_core_graph.png", 
           path = "C:/Users/nblan/Desktop/Honors_project/R/Graphs", 
           height = 6, 
           width = 10)

# a <- new_water_data %>%
#   filter(sample_type %in% c("Twig", "Core", "well_water", "precip", "Soil"), plant_type == c("resprout", "")) %>%
#   ggplot(aes(x = dO, y = dD, col = full_sample_type)) +
#     geom_point(alpha = 1, show.legend = FALSE) +
#     stat_ellipse() +
#     geom_abline(aes(slope = 7.82, intercept = 9.42, lty = "Local Meteoric Water Line")) +
#     labs(title = "δD and δ18O of core samples", x = "δ18O (‰)", y = "δD (‰)") +
#     theme_pubr(legend = "right") +
#     scale_color_discrete(name = "Sample Type") +
#     scale_linetype(name = "Local Meteoric Water Line") +
#     ggsave("δD_and_d18O_full_core_graph.png", 
#            path = "C:/Users/nblan/Desktop/Honors_project/R/Graphs", 
#            height = 6, 
#            width = 10)
# 
# b<- new_water_data %>%
#   filter(sample_type %in% c("Twig", "Core", "well_water", "precip", "Soil"), plant_type == c("not_resprout", "")) %>%
#   ggplot(aes(x = dO, y = dD, col = full_sample_type)) +
#     geom_point(alpha = 1, show.legend = FALSE) +
#     stat_ellipse() +
#     geom_abline(aes(slope = 7.82, intercept = 9.42, lty = "Local Meteoric Water Line")) +
#     labs(title = "δD and δ18O of core samples", x = "δ18O (‰)", y = "δD (‰)") +
#     theme_pubr(legend = "right") +
#     scale_color_discrete(name = "Sample Type") +
#     scale_linetype(name = "Local Meteoric Water Line") +
#     ggsave("δD_and_d18O_full_core_graph.png", 
#            path = "C:/Users/nblan/Desktop/Honors_project/R/Graphs", 
#            height = 6, 
#            width = 10)
# 
# library(cowplot)
# plot_grid(a, b, 
#           labels = "AUTO")
```


```{r}
# C & N stuff

# C
c_n_data %>%
  ggplot(aes(x = plant_type, y = d13C, col = plant_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(title = "d13C of leaves from resprouts and non-resprouts", x = "Plant Type", y = "d13C (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Plant Type", labels = c("Not Resprout", "Resprout")) +
  ggsave("d13c_boxplot.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)

# N
c_n_data %>%
  ggplot(aes(x = plant_type, y = d15N, col = plant_type)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test") +
  labs(title = "d15N of leaves from resprouts and non-resprouts", x = "Plant Type", y = "d15N (‰)") +
  theme_pubclean() +
  scale_color_wsj(name = "Plant Type", labels = c("Not Resprout", "Resprout")) +
  ggsave("d15n_boxplot.png", 
         path = "C:/Users/nblan/Desktop/Honors_Project/R/Graphs", 
         height = 6, 
         width = 6)
```



# RGBIF STUFF AND MAPPING

```{r}
# GENERATE GBIF KEY AND READ IN OCCURANCES (UNCOMMENT LINE UNDER KEY TO OBTAIN DATA FOR FIRST TIME)
key <- name_backbone(name="Arctostaphylos glandulosa")$speciesKey
res <- occ_data(taxonKey = key, hasCoordinate = TRUE, stateProvince = "California", limit = 4000)

res_rds <- saveRDS(res, "res.rds")
```

```{r}
arcto_data <- readRDS("res.rds")
cali_border <- st_read("C:/Users/nblan/Desktop/Honors_Project/R/GISLayers/CA_State_TIGER2016.shp")
```

```{r}
arcto_tibble <- tibble(arcto_data$data) %>%
  filter(geodeticDatum == "WGS84", 
         taxonomicStatus == "ACCEPTED", 
         is.na(year) != TRUE, 
         year %in% c(1990:2020))

arcto_points <- SpatialPoints(arcto_tibble[, c("decimalLongitude", "decimalLatitude")])

manzanita_filtered <- manzanita %>%
  filter(site == "S2")
my_manz_pts <- SpatialPoints(manzanita_filtered[, c("longitude", "latitude")])
```

```{r}
# mapping
tm_style("classic")
map1 <- tm_shape(cali_border) +
  tm_borders() +
  tm_fill(col = "lightgreen", alpha = 0.4) +
tm_shape(arcto_points) +
  tm_dots(size = 0.3, shape = 1, alpha = 0.3, clustering = TRUE) +
tm_shape(my_manz_pts) +
  tm_dots(size = 4, shape = 7, col = "red") +
tm_layout(bg.color = "skyblue")

tmap_save(map1, "C:/Users/nblan/Desktop/Honors_Project/R/Graphs/cali_arcto_map1.png", 
          height = 5, 
          width = 5)
```

## MAPPING STUFF


```{r}
# Load in the shape files
border <- st_read("C:/Users/nblan/Desktop/Honors_Project/R/GISLayers/PWD_BASE_Jursd_Boundaries_PepperwoodPreserve.shp")

tributaries <- st_read("C:/Users/nblan/Desktop/Honors_Project/R/GISLayers/PWD_BASE_Env_Hydro_RR_tributaries.shp")

road <- st_read("C:/Users/nblan/Desktop/Honors_Project/R/GISLayers/PWD_BASE_Infstr_Roads.shp")

fire <- st_read("C:/Users/nblan/Desktop/Honors_Project/R/GISLayers/PWD_KincadeFire_fullPerimeter.shp")

manzanita_points <- st_read(manzanita)
```


```{r}
# Generate a map of Pepperwood

map2 <- tm_shape(border) +
  tm_borders() +
  tm_fill(col = "green", alpha = 0.7) +
tm_shape(my_manz_pts) +
  tm_dots(size = 4, shape = 7, col = "red") +
tm_compass(type = "rose", 
           position = c("right", "top"), 
           color.light = "yellow", 
           color.dark = "darkblue") +
tm_layout(bg.color = "skyblue")

tmap_save(map2, "C:/Users/nblan/Desktop/Honors_Project/R/Graphs/cali_arcto_map2.png", 
          height = 6, 
          width = 6)
  
```

## ANOVAS

```{r}
# Is there a difference in gross horsepower due to # of forward gears?

hist(mtcars$hp) # check to make sure data are noramally distributed
shapiro.test(mtcars$hp) # if the P value is > 0.05 your data is normally distrbuted

aov_hp = aov(mtcars$hp ~ mtcars$gear) # save your anova results table (output) 

summary(aov_hp) # sumarize your results 

# post-hoc test (test on the results of another test). The one-way anova only gives us a p value for all groups, saying there is a significant difference or not somewhere in the data tested. It does not tell you which groups are significantly different
?TukeyHSD
TukeyHSD(aov_hp)
```



```{r}
# ANOVA for cores + twigs dD

core_twig_temporal <- temporal_data %>%
  filter(sample_type == c("Core", "Twig"))

hist(core_twig_temporal$dD)
shapiro.test(core_twig_temporal$dD)

coretwig_anova_dD = aov(dD ~ sample_type + date, data = core_twig_temporal)
summary(coretwig_anova_dD)

TukeyHSD(coretwig_anova_dD)
```
# http://rcompanion.org/rcompanion/d_07.html

 # NESTED ANOVA
```{r}
if(!require(nlme)){install.packages("nlme")}
if(!require(multcomp)){install.packages("multcomp")}
if(!require(multcompView)){install.packages("multcompView")}
if(!require(lsmeans)){install.packages("lsmeans")}
if(!require(lme4)){install.packages("lme4")}
if(!require(lmerTest)){install.packages("lmerTest")}
if(!require(TukeyC)){install.packages("TukeyC")}


```







